# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ckan_browser_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CKANBrowserDialogBase(object):
    def setupUi(self, CKANBrowserDialogBase):
        CKANBrowserDialogBase.setObjectName("CKANBrowserDialogBase")
        CKANBrowserDialogBase.setWindowModality(QtCore.Qt.ApplicationModal)
        CKANBrowserDialogBase.resize(800, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CKANBrowserDialogBase.sizePolicy().hasHeightForWidth())
        CKANBrowserDialogBase.setSizePolicy(sizePolicy)
        CKANBrowserDialogBase.setMinimumSize(QtCore.QSize(800, 620))
        CKANBrowserDialogBase.setMaximumSize(QtCore.QSize(2300, 1600))
        CKANBrowserDialogBase.setModal(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CKANBrowserDialogBase)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.IDC_lineSearch = QtWidgets.QLineEdit(CKANBrowserDialogBase)
        self.IDC_lineSearch.setObjectName("IDC_lineSearch")
        self.horizontalLayout_7.addWidget(self.IDC_lineSearch)
        self.pushButton_3 = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton_3.setMinimumSize(QtCore.QSize(14, 22))
        self.pushButton_3.setMaximumSize(QtCore.QSize(18, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.IDC_bSearch = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.IDC_bSearch.setObjectName("IDC_bSearch")
        self.verticalLayout.addWidget(self.IDC_bSearch)
        self.IDC_bListAll = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.IDC_bListAll.setObjectName("IDC_bListAll")
        self.verticalLayout.addWidget(self.IDC_bListAll)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton_4.setMinimumSize(QtCore.QSize(14, 22))
        self.pushButton_4.setMaximumSize(QtCore.QSize(18, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.IDC_listGroup = QtWidgets.QListWidget(CKANBrowserDialogBase)
        self.IDC_listGroup.setMinimumSize(QtCore.QSize(160, 0))
        self.IDC_listGroup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.IDC_listGroup.setObjectName("IDC_listGroup")
        self.verticalLayout.addWidget(self.IDC_listGroup)
        self.IDC_lblApiUrl = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblApiUrl.setMinimumSize(QtCore.QSize(0, 60))
        self.IDC_lblApiUrl.setFrameShape(QtWidgets.QFrame.Box)
        self.IDC_lblApiUrl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.IDC_lblApiUrl.setWordWrap(True)
        self.IDC_lblApiUrl.setObjectName("IDC_lblApiUrl")
        self.verticalLayout.addWidget(self.IDC_lblApiUrl)
        self.IDC_lblCacheDir = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblCacheDir.setMinimumSize(QtCore.QSize(0, 60))
        self.IDC_lblCacheDir.setFrameShape(QtWidgets.QFrame.Box)
        self.IDC_lblCacheDir.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.IDC_lblCacheDir.setWordWrap(True)
        self.IDC_lblCacheDir.setObjectName("IDC_lblCacheDir")
        self.verticalLayout.addWidget(self.IDC_lblCacheDir)
        self.IDC_lblVersion = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblVersion.setMinimumSize(QtCore.QSize(0, 0))
        self.IDC_lblVersion.setFrameShape(QtWidgets.QFrame.Box)
        self.IDC_lblVersion.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.IDC_lblVersion.setObjectName("IDC_lblVersion")
        self.verticalLayout.addWidget(self.IDC_lblVersion)
        self.IDC_bDisclaimer = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.IDC_bDisclaimer.setObjectName("IDC_bDisclaimer")
        self.verticalLayout.addWidget(self.IDC_bDisclaimer)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.IDC_lblSuchergebnisse = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblSuchergebnisse.setObjectName("IDC_lblSuchergebnisse")
        self.verticalLayout_3.addWidget(self.IDC_lblSuchergebnisse)
        self.IDC_listResults = QtWidgets.QListWidget(CKANBrowserDialogBase)
        self.IDC_listResults.setMinimumSize(QtCore.QSize(270, 0))
        self.IDC_listResults.setObjectName("IDC_listResults")
        self.verticalLayout_3.addWidget(self.IDC_listResults)
        self.IDC_lblPage = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblPage.setAlignment(QtCore.Qt.AlignCenter)
        self.IDC_lblPage.setObjectName("IDC_lblPage")
        self.verticalLayout_3.addWidget(self.IDC_lblPage)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton.setMinimumSize(QtCore.QSize(15, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(15, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.IDC_textDetails = QtWidgets.QTextEdit(CKANBrowserDialogBase)
        self.IDC_textDetails.setMinimumSize(QtCore.QSize(250, 160))
        self.IDC_textDetails.setObjectName("IDC_textDetails")
        self.verticalLayout_4.addWidget(self.IDC_textDetails)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton_5.setMinimumSize(QtCore.QSize(14, 22))
        self.pushButton_5.setMaximumSize(QtCore.QSize(18, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.IDC_listRessources = QtWidgets.QListWidget(CKANBrowserDialogBase)
        self.IDC_listRessources.setMinimumSize(QtCore.QSize(0, 160))
        self.IDC_listRessources.setObjectName("IDC_listRessources")
        self.verticalLayout_4.addWidget(self.IDC_listRessources)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.IDC_lblRessourceURL = QtWidgets.QLabel(CKANBrowserDialogBase)
        self.IDC_lblRessourceURL.setObjectName("IDC_lblRessourceURL")
        self.horizontalLayout_9.addWidget(self.IDC_lblRessourceURL)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.pushButton_6 = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.pushButton_6.setMinimumSize(QtCore.QSize(14, 22))
        self.pushButton_6.setMaximumSize(QtCore.QSize(18, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.IDC_plainTextLink = QtWidgets.QPlainTextEdit(CKANBrowserDialogBase)
        self.IDC_plainTextLink.setMinimumSize(QtCore.QSize(0, 50))
        self.IDC_plainTextLink.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.IDC_plainTextLink.setReadOnly(True)
        self.IDC_plainTextLink.setPlainText("")
        self.IDC_plainTextLink.setObjectName("IDC_plainTextLink")
        self.horizontalLayout_6.addWidget(self.IDC_plainTextLink)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.IDC_bCopy = QtWidgets.QToolButton(CKANBrowserDialogBase)
        self.IDC_bCopy.setText("")
        self.IDC_bCopy.setIconSize(QtCore.QSize(24, 24))
        self.IDC_bCopy.setObjectName("IDC_bCopy")
        self.verticalLayout_2.addWidget(self.IDC_bCopy)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.IDC_bLoadResource = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.IDC_bLoadResource.setObjectName("IDC_bLoadResource")
        self.verticalLayout_4.addWidget(self.IDC_bLoadResource)
        self.IDC_bClose = QtWidgets.QPushButton(CKANBrowserDialogBase)
        self.IDC_bClose.setObjectName("IDC_bClose")
        self.verticalLayout_4.addWidget(self.IDC_bClose)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(CKANBrowserDialogBase)
        self.IDC_lineSearch.textChanged['QString'].connect(CKANBrowserDialogBase.searchtextchanged)
        self.IDC_listResults.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(CKANBrowserDialogBase.resultitemchanged)
        self.IDC_bLoadResource.clicked.connect(CKANBrowserDialogBase.load_resource_clicked)
        self.IDC_bClose.clicked.connect(CKANBrowserDialogBase.close_dlg)
        self.IDC_listGroup.itemChanged['QListWidgetItem*'].connect(CKANBrowserDialogBase.list_group_item_changed)
        self.IDC_bSearch.clicked.connect(CKANBrowserDialogBase.suchen)
        self.IDC_listGroup.itemActivated['QListWidgetItem*'].connect(CKANBrowserDialogBase.category_item_clicked)
        self.pushButton.clicked.connect(CKANBrowserDialogBase.previous_page_clicked)
        self.pushButton_2.clicked.connect(CKANBrowserDialogBase.next_page_clicked)
        self.IDC_bListAll.clicked.connect(CKANBrowserDialogBase.list_all_clicked)
        self.IDC_bDisclaimer.clicked.connect(CKANBrowserDialogBase.show_disclaimer)
        self.pushButton_3.clicked.connect(CKANBrowserDialogBase.help_ttip_search)
        self.pushButton_4.clicked.connect(CKANBrowserDialogBase.help_ttip_filter)
        self.pushButton_5.clicked.connect(CKANBrowserDialogBase.help_ttip_data_list)
        self.IDC_bCopy.clicked.connect(CKANBrowserDialogBase.copy_clipboard)
        self.IDC_listRessources.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(CKANBrowserDialogBase.resource_item_changed)
        self.pushButton_6.clicked.connect(CKANBrowserDialogBase.help_ttip_resource)
        QtCore.QMetaObject.connectSlotsByName(CKANBrowserDialogBase)

    def retranslateUi(self, CKANBrowserDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CKANBrowserDialogBase.setWindowTitle(_translate("CKANBrowserDialogBase", "dlg_base_title"))
        self.label.setText(_translate("CKANBrowserDialogBase", "dlg_base_search_term"))
        self.pushButton_3.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_search"))
        self.pushButton_3.setText(_translate("CKANBrowserDialogBase", "?"))
        self.IDC_bSearch.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_strt_srch"))
        self.IDC_bListAll.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_show"))
        self.IDC_bListAll.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_show_all"))
        self.label_5.setText(_translate("CKANBrowserDialogBase", "dlg_base_filter_to"))
        self.pushButton_4.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_filter"))
        self.pushButton_4.setText(_translate("CKANBrowserDialogBase", "?"))
        self.IDC_lblApiUrl.setText(_translate("CKANBrowserDialogBase", "IDC_lblApiUrl"))
        self.IDC_lblCacheDir.setText(_translate("CKANBrowserDialogBase", "IDC_lblCacheDir"))
        self.IDC_lblVersion.setText(_translate("CKANBrowserDialogBase", "IDC_lblVersion"))
        self.IDC_bDisclaimer.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_disclaimer"))
        self.IDC_lblSuchergebnisse.setText(_translate("CKANBrowserDialogBase", "dlg_base_srch_rslt"))
        self.IDC_lblPage.setText(_translate("CKANBrowserDialogBase", "IDC_lblPage"))
        self.pushButton.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_prev"))
        self.pushButton.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_lt"))
        self.pushButton_2.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_next"))
        self.pushButton_2.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_gt"))
        self.label_3.setText(_translate("CKANBrowserDialogBase", "dlg_base_descr"))
        self.label_4.setText(_translate("CKANBrowserDialogBase", "dlg_base_data_list"))
        self.pushButton_5.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_data_list"))
        self.pushButton_5.setText(_translate("CKANBrowserDialogBase", "?"))
        self.IDC_lblRessourceURL.setText(_translate("CKANBrowserDialogBase", "dlg_base_ressource"))
        self.pushButton_6.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_resource"))
        self.pushButton_6.setText(_translate("CKANBrowserDialogBase", "?"))
        self.IDC_bCopy.setToolTip(_translate("CKANBrowserDialogBase", "dlg_base_ttip_copy"))
        self.IDC_bLoadResource.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_load_data"))
        self.IDC_bClose.setText(_translate("CKANBrowserDialogBase", "dlg_base_btn_close"))

